# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  depCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dependencyCheckAnalyze
    - name: Backup JSON Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report.json
        path: ./build/reports/dependency-check-report.json

  owasp_report:
    needs: [depCheck]
    runs-on: ubuntu-20.04
    name: Create a report with an overview of the vulnerabilities per dependency
    steps:
      - uses: actions/checkout@v2
        with:
          repository: perpk/owasp-report-custom-render
      - uses: actions/download-artifact@v2
        with:
          name: dependency-check-report.json
          path: ./
      - name: Check where we are
        run: pwd
      - name: Check what the dir contents are
        run: ls -lah
      - name: Change perms on downloaded report file
        run: chmod u+rwx dependency-check-report.json
      - name: Run Report Creation
        uses: ./action.yml
        with:
          owasp-json-report: ./dependency-check-report.json

